### ISSUE TITLE
Additions to `structure` bundle

### ISSUE THREAD

**Issue by benjamin-kirkbride** [simonw/strip-tags#17]
What do we think about adding table and list tags?

**Comment by simonw** [comment]
I think those should go in separate bundles - `--tables` and `--lists`. Then people can run all three if they want to.

**Comment by simonw** [comment]
For tables:

- `table`
- `tr`
- `td`
- `th``
- `thead`
- `tbody`
- `tfoot`
- `caption`
- `colgroup`
- `col`

For lists:

- `ul`
- `ol`
- `li`
- `dl`
- `dt`
- `dd`

**Comment by benjamin-kirkbride** [comment]
Seems reasonable to me. Is there a way to use the bundles as a lib?

Also, should we consider things like emphasis, italics, underline, etc? I know most of that stuff is CSS these days, so maybe not worth it..

**Comment by simonw** [comment]
> Seems reasonable to me. Is there a way to use the bundles as a lib?

Yes, the bundles are currently expanded inside the `strip_tags()` function here:

https://github.com/simonw/strip-tags/blob/09996811fa21553de824743d31d5eda49394e599/strip_tags/lib.py#L141-L149

> Also, should we consider things like emphasis, italics, underline, etc? I know most of that stuff is CSS these days, so maybe not worth it.

We could add a bundle for those, not sure what it should be called though.
