### ISSUE TITLE
`icdiff` can tank performance when testing against larger inputs

### ISSUE THREAD

**Issue by benjamin-kirkbride** [simonw/strip-tags#22]
Using an html dump of simonwillison.net for a single test results in the test taking nearly a minute on my machine when `icdiff` is enabled. When I run `pytest` with the `-p no:icdiff` flag, it takes about a second.

Used the following command to track this down, for posterity:
`time python -m cProfile -o prof.prof -m pytest --cov=strip_tags --cov-branch --cov-report term-missing -x --lf tests/test_lib/ -k foo`

**Comment by simonw** [comment]
Since it was purely there as a tiny test DC enhancement I've dropped it.
