### ISSUE TITLE
Exclude tags option: -r/--remove

### ISSUE THREAD

**Issue by HaveF** [simonw/strip-tags#24]
I like this tool, thank you, Simon.

In most of time, it seems that we don't know where is the the main part of a common page. 

But we may know we don't want `aside`, we don't want 'header',  'footer',  'nav'...

So, I believe exclude tags options may useful?

**Comment by simonw** [comment]
This is interesting - yeah, it makes sense to me.

**Comment by simonw** [comment]
A `-x/--exclude` option could fit here. Here's what `--help` would look like with that:

```
Options:
  --version             Show the version and exit.
  -i, --input FILENAME
  -m, --minify          Minify whitespace
  -x, --exclude TEXT    Exclude content in these selectors
  -t, --keep-tag TEXT   Keep these <tags>
  --all-attrs           Include all attributes on kept tags
  --first               First element matching the selectors
  --help                Show this message and exit.
```

**Comment by simonw** [comment]
Demo:
```bash
curl -s https://datasette.io/ | strip-tags -r nav -r footer -m
```
