### ISSUE TITLE
Relative performance of --minify

### ISSUE THREAD

**Issue by benjamin-kirkbride** [simonw/strip-tags#8]
When using `strip-tags` with it's siblings using the patterns described in https://simonwillison.net/2023/May/18/cli-tools-for-llms/, what effect does the `--minify` argument have on the final result? My assumption is that the difference is pretty minimal.

I ran `curl -s https://www.endpointdev.com/blog/2015/12/postgres-checksum-performance-impact/ | strip-tags --minify .page | ttok` and `curl -s https://www.endpointdev.com/blog/2015/12/postgres-checksum-performance-impact/ | strip-tags .page | ttok` and got a difference of...  25 tokens, or about a 1% reduction. This was much smaller of a token difference than I expected, so I would also not expect a significant difference in the performance of `llm`, but am interested to hear other's thoughts.

**Comment by simonw** [comment]
This is a bit surprising.

I had a go with the tokenizer tool I built to see what the tokens for different amounts of whitespace look like:

<img width="978" alt="image" src="https://github.com/simonw/strip-tags/assets/9599/ea37e670-ef4e-4509-86d6-bc07f114d0d6">

Input text was:

```
This text
  has spaces
    four spaces
      six spaces then two newlines

That was two newlines, now four newlines





```
Pasted into https://observablehq.com/@simonw/gpt-tokenizer

I thought maybe things like four spaces or multiple newlines would have a single token assigned to them, but it looks like they don't.

**Comment by simonw** [comment]
https://simonwillison.net/2018/Dec/19/fast-autocomplete-search/ is quite a complex page.

    curl 'https://simonwillison.net/2018/Dec/19/fast-autocomplete-search/' > /tmp/search.html

```
% cat /tmp/search.html | strip-tags | ttok
6003
% cat /tmp/search.html | strip-tags -m | ttok
5745
```
So that's a reduction of `(6003 - 5745) / 6003 * 100` = 4.29%

**Comment by simonw** [comment]
Yeah the `--minify` feature is less effective than I had expected. I still think it's worthwhile sometimes, because tokens are expensive and it can make the difference between fitting in a 4,000 context window and not fitting - but I'm cancelling my plan to make `-m` the default behaviour since it doesn't feel like it's a big enough win to justify that.
